name = "arch-api"
main = "src/index.ts"
compatibility_date = "2026-03-05"
compatibility_flags = ["nodejs_als", "nodejs_compat"]

[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "arch"
database_id = "f50e22cf-2ef5-4e65-b10e-b82fcceb8fe2"
migrations_dir = "migrations"

[[durable_objects.bindings]]
name = "RATE_LIMITER"
class_name = "RateLimiter"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["RateLimiter"]

[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "arch-storage"

[triggers]
crons = ["0 0 * * *"]

[vars]
APP_ENV = "development"
APP_URL = "http://localhost:5173"
API_URL = "http://127.0.0.1:8787"

[[env.production.d1_databases]]
binding = "DB"
database_name = "arch"
database_id = "f50e22cf-2ef5-4e65-b10e-b82fcceb8fe2"
migrations_dir = "migrations"

[[env.production.durable_objects.bindings]]
name = "RATE_LIMITER"
class_name = "RateLimiter"

[[env.production.r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "arch-storage"

[env.production.vars]
APP_ENV = "production"
APP_URL = "https://arch.wellnesscorporateplan.pt"
API_URL = "https://arch.wellnesscorporateplan.pt/api"
